// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwwxO16_ABNai81yrGvsuoYS0NXzCsnhI',
    appId: '1:999298464678:android:a36f82b7d59cacc1ddad67',
    messagingSenderId: '999298464678',
    projectId: 'green-chat-dbf96',
    storageBucket: 'green-chat-dbf96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDclp7Yg-xVmLmbNz6E27hre34kUqBszTQ',
    appId: '1:999298464678:ios:c7ff0a64955853ddddad67',
    messagingSenderId: '999298464678',
    projectId: 'green-chat-dbf96',
    storageBucket: 'green-chat-dbf96.appspot.com',
    iosBundleId: 'com.example.greenChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5j5TTNhHg4a6EpH8aOXkU6Cmja9stWZE',
    appId: '1:999298464678:web:5586a041660e8ac5ddad67',
    messagingSenderId: '999298464678',
    projectId: 'green-chat-dbf96',
    authDomain: 'green-chat-dbf96.firebaseapp.com',
    storageBucket: 'green-chat-dbf96.appspot.com',
    measurementId: 'G-BJ9H090236',
  );

}